/* Generated by radium — do not edit by hand. */
/* Run `npm run tokens` (or `radium build`) to regenerate. */

export const CONTEXTS = ["default", "dark", "light"] as const

export type Context = (typeof CONTEXTS)[number]
