/* Generated by radium — do not edit by hand. */
/* Run `npm run tokens` (or `radium build`) to regenerate. */

export const FONTS = [
  { family: "Crimson Text", weights: [400] },
  { family: "Montserrat", weights: [400, 600] },
  { family: "Source Code Pro", weights: [400] },
] as const

export type FontDef = { family: string; weights: number[] }
