import { ROOT_CONTEXT } from "./collapse.js"
import type { DtcgNode } from "./types.js"

/** Name the `$root` context maps to in generated output (matches the `:root` CSS scope). */
export const DEFAULT_CONTEXT_NAME = "default"

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v)
}

function isContextWrapper(v: unknown): boolean {
  return isObject(v) && "$value" in v
}

/**
 * Extract the distinct context names declared anywhere in a DTCG token tree.
 *
 * Walks to each logical token (a node with a `$root` context wrapper) and collects the
 * context keys it declares (`$root`, `dark`, `light`, …). `$root` is mapped to
 * `"default"` and placed first; the rest follow in first-seen order, deduped.
 */
export function getContexts(tokens: DtcgNode, rootName: string = DEFAULT_CONTEXT_NAME): string[] {
  const order: string[] = []
  const seen = new Set<string>()

  const walk = (node: DtcgNode): void => {
    if (ROOT_CONTEXT in node && isContextWrapper(node[ROOT_CONTEXT])) {
      for (const key of Object.keys(node)) {
        if (key.startsWith("$") && key !== ROOT_CONTEXT) continue
        if (isContextWrapper(node[key]) && !seen.has(key)) {
          seen.add(key)
          order.push(key)
        }
      }
      return
    }
    for (const key of Object.keys(node)) {
      if (key.startsWith("$")) continue
      const child = node[key]
      if (isObject(child)) walk(child as DtcgNode)
    }
  }

  walk(tokens)

  const mapped = order.map((k) => (k === ROOT_CONTEXT ? rootName : k))
  return [...new Set([rootName, ...mapped])]
}

/** Render the generated `contexts.ts` module emitted alongside `variables.css`. */
export function formatContextsModule(contexts: string[]): string {
  const list = contexts.map((c) => JSON.stringify(c)).join(", ")
  return (
    "/* Generated by radium — do not edit by hand. */\n" +
    "/* Run `npm run tokens` (or `radium build`) to regenerate. */\n\n" +
    `export const CONTEXTS = [${list}] as const\n\n` +
    "export type Context = (typeof CONTEXTS)[number]\n"
  )
}
