import { flattenForContext } from "./collapse.js"
import { cssNames, usesExportNames } from "./name.js"
import { resolveReferences } from "./resolve.js"
import { serializeValue } from "./serialize.js"
import type { ResolvedCssOptions } from "./options.js"
import type { DtcgNode } from "./types.js"

/** An ordered map of CSS variable name → serialized value for one context. */
type VarMap = Map<string, string>

/** Build the `name → cssValue` map for a single context. */
function buildContextVars(
  tokens: DtcgNode,
  context: string,
  useExportName: boolean,
  options: ResolvedCssOptions,
): VarMap {
  const flat = resolveReferences(flattenForContext(tokens, context))
  const vars: VarMap = new Map()
  for (const token of flat.values()) {
    const names = cssNames(token, options.nameExtension, useExportName)
    if (names.length === 0) continue
    const value = serializeValue(token.value, options)
    for (const name of names) vars.set(name, value)
  }
  return vars
}

function renderBlock(selector: string, vars: Iterable<[string, string]>): string {
  const lines = [...vars].map(([name, value]) => `  --${name}: ${value};`)
  if (lines.length === 0) return ""
  return `${selector} {\n${lines.join("\n")}\n}`
}

/**
 * Convert a DTCG token tree into a scoped CSS string. The first context in
 * `options.contexts` is the base (emitted in full); every other context emits
 * only the variables whose value differs from the base.
 */
export function emitCss(tokens: DtcgNode, options: ResolvedCssOptions): string {
  const contextNames = Object.keys(options.contexts)
  const useExportName = usesExportNames(
    flattenForContext(tokens, contextNames[0]!).values(),
    options.nameExtension,
  )

  const [baseContext, ...overrideContexts] = contextNames
  const baseVars = buildContextVars(tokens, baseContext!, useExportName, options)

  const blocks: string[] = [renderBlock(options.contexts[baseContext!]!, baseVars)]

  for (const context of overrideContexts) {
    const vars = buildContextVars(tokens, context, useExportName, options)
    const overrides = [...vars].filter(([name, value]) => baseVars.get(name) !== value)
    const block = renderBlock(options.contexts[context]!, overrides)
    if (block) blocks.push(block)
  }

  const header =
    "/* Generated by radium — do not edit by hand. */\n" +
    "/* Run `npm run tokens` (or `radium build`) to regenerate. */\n"
  return `${header}\n${blocks.filter(Boolean).join("\n\n")}\n`
}
