import { flattenForContext, ROOT_CONTEXT } from "./collapse.js"
import { resolveReferences } from "./resolve.js"
import type { DtcgNode, TokenValue } from "./types.js"

/** A web font to load: a family name and the weights it is used at. */
export interface FontDef {
  family: string
  weights: number[]
}

/** Generic CSS family keywords that are never loaded as web fonts. */
const GENERIC_FAMILIES = new Set([
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
  "ui-serif",
  "ui-sans-serif",
  "ui-monospace",
  "ui-rounded",
  "math",
  "emoji",
  "fangsong",
  "inherit",
  "initial",
  "unset",
])

const DEFAULT_WEIGHT = 400

/** Resolve a fontFamily token value to a primary family name (first non-generic), or null. */
function primaryFamily(value: TokenValue): string | null {
  const candidates = Array.isArray(value) ? value : [value]
  for (const candidate of candidates) {
    if (typeof candidate !== "string") continue
    const name = candidate.trim().replace(/^['"]|['"]$/g, "")
    if (name && !GENERIC_FAMILIES.has(name.toLowerCase())) return name
  }
  return null
}

function parentPath(path: string): string {
  const i = path.lastIndexOf(".")
  return i === -1 ? "" : path.slice(0, i)
}

/**
 * Extract the web fonts referenced by a DTCG token tree.
 *
 * Collects every distinct `fontFamily` value (references resolved), then derives each
 * family's weights from the semantic typography composites — a group whose `font-family`
 * resolves to that family contributes its sibling `font-weight`. Families used without an
 * accompanying weight default to `[400]`. Result is sorted by family for determinism.
 */
export function getFonts(tokens: DtcgNode): FontDef[] {
  const flat = resolveReferences(flattenForContext(tokens, ROOT_CONTEXT))

  const families = new Set<string>()
  const familyByParent = new Map<string, string>()
  const weightByParent = new Map<string, number>()

  for (const token of flat.values()) {
    if (token.type === "fontFamily") {
      const family = primaryFamily(token.value)
      if (family) {
        families.add(family)
        familyByParent.set(parentPath(token.path), family)
      }
    } else if (token.type === "fontWeight" && typeof token.value === "number") {
      weightByParent.set(parentPath(token.path), token.value)
    }
  }

  const weightsByFamily = new Map<string, Set<number>>()
  for (const [parent, family] of familyByParent) {
    const weight = weightByParent.get(parent)
    if (weight === undefined) continue
    const set = weightsByFamily.get(family) ?? new Set<number>()
    set.add(weight)
    weightsByFamily.set(family, set)
  }

  return [...families].sort().map((family) => {
    const weights = weightsByFamily.get(family)
    return {
      family,
      weights: weights ? [...weights].sort((a, b) => a - b) : [DEFAULT_WEIGHT],
    }
  })
}

/** Render the generated `fonts.ts` module emitted alongside `variables.css`. */
export function formatFontsModule(fonts: FontDef[]): string {
  const entries = fonts
    .map((f) => `  { family: ${JSON.stringify(f.family)}, weights: [${f.weights.join(", ")}] },`)
    .join("\n")
  return (
    "/* Generated by radium — do not edit by hand. */\n" +
    "/* Run `npm run tokens` (or `radium build`) to regenerate. */\n\n" +
    `export const FONTS = [\n${entries}\n] as const\n\n` +
    "export type FontDef = { family: string; weights: number[] }\n"
  )
}
